import _Home from "./Home";
import _Cart from "./Cart";
import _Search from "./Search";
import _AboutUs from "./AboutUs";
import _Payment from "./Payment";
import _Language from "./Language";
import _Checkout from "./Checkout";
import _MyOrders from "./MyOrders";
import _ContactUs from "./ContactUs";
import _NewAddress from "./NewAddress";
import _ShowStores from "./ShowStores";
import _ItemDetail from "./ItemDetail";
import _Categories from "./Categories";
import _PinLocation from "./PinLocation";
import _MyAddresses from "./MyAddresses";
import _Verification from "./Verification";
import _OnBoardingCity from "./OnBoarding/City";
import _OnBoardingCategory from "./OnBoarding/Category";

export const Home = _Home;
export const Cart = _Cart;
export const Search = _Search;
export const AboutUs = _AboutUs;
export const Payment = _Payment;
export const Checkout = _Checkout;
export const Language = _Language;
export const MyOrders = _MyOrders;
export const ContactUs = _ContactUs;
export const NewAddress = _NewAddress;
export const ShowStores = _ShowStores;
export const ItemDetail = _ItemDetail;
export const Categories = _Categories;
export const MyAddresses = _MyAddresses;
export const PinLocation = _PinLocation;
export const Verification = _Verification;
export const OnBoardingCity = _OnBoardingCity;
export const OnBoardingCategory = _OnBoardingCategory;
