import _Home from "./Home";
import _Cart from "./Cart";
import _Search from "./Search";
import _Language from "./Language";
import _Checkout from "./Checkout";
import _ShowStores from "./ShowStores";
import _ItemDetail from "./ItemDetail";
import _Categories from "./Categories";
import _OnBoardingCity from "./OnBoarding/City";
import _OnBoardingCategory from "./OnBoarding/Category";

export const Home = _Home;
export const Cart = _Cart;
export const Search = _Search;
export const Checkout = _Checkout;
export const Language = _Language;
export const ShowStores = _ShowStores;
export const ItemDetail = _ItemDetail;
export const Categories = _Categories;
export const OnBoardingCity = _OnBoardingCity;
export const OnBoardingCategory = _OnBoardingCategory;
