export const CLEAR_CART = "CLEAR_CART";
export const SAVE_ADDRESS = "SAVE_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const SAVE_USER_DATA = "SAVE_USER_DATA";
export const CLEAR_USER_DATA = "CLEAR_USER_DATA";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
