import A from "react-native-vector-icons/Entypo";
import C from "react-native-vector-icons/Feather";
import B from "react-native-vector-icons/Ionicons";
import O from "react-native-vector-icons/Octicons";
import D from "react-native-vector-icons/Fontisto";
import E from "react-native-vector-icons/EvilIcons";
import F from "react-native-vector-icons/AntDesign";
import G from "react-native-vector-icons/FontAwesome";
import L from "react-native-vector-icons/FontAwesome5";
import H from "react-native-vector-icons/MaterialIcons";
import I from "react-native-vector-icons/SimpleLineIcons";
import J from "react-native-vector-icons/MaterialCommunityIcons";

export const Icon = B;
export const Entypo = A;
export const Feather = C;
export const Octicons = O;
export const Fontisto = D;
export const EvilIcons = E;
export const AntDesign = F;
export const FontAwesome = G;
export const FontAwesome5 = L;
export const MaterialIcons = H;
export const SimpleLineIcons = I;
export const MaterialCommunityIcons = J;
